name: .NET Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  SOLUTION: ./CICDProject/CICDProject.sln
  PROJECT: ./CICDProject/CICDProject/CICDProject.csproj
  TEST_PROJECT: ./CICDProject/CICDApi.UnitTests/CICDApi.UnitTests.csproj

jobs:
  build-test-publish:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration Release --no-restore

      - name: Run NUnit Tests with Coverage
        run: |
          dotnet test ${{ env.TEST_PROJECT }} \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory TestResults \
            --collect:"XPlat Code Coverage"

      # Debug (remove later if you want)
      - name: Show Generated Files
        run: |
          echo "Current Directory"
          pwd

          echo ""
          echo "Coverage Files"
          find . -name "coverage.cobertura.xml"

          echo ""
          echo "TRX Files"
          find . -name "*.trx"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/*.trx

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        run: |
          reportgenerator \
          "-reports:**/coverage.cobertura.xml" \
          "-targetdir:coveragereport" \
          "-reporttypes:Html;MarkdownSummary"

      - name: Display Coverage Summary
        run: cat coveragereport/Summary.md

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: CodeCoverageReport
          path: coveragereport

      - name: Publish Web API
        run: |
          dotnet publish ${{ env.PROJECT }} \
            --configuration Release \
            --no-build \
            --output publish

      - name: Upload Published API
        uses: actions/upload-artifact@v4
        with:
          name: PublishedAPI
          path: publish