name: .NET Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore Packages
      run: dotnet restore ./CICDProject/CICDProject/CICDProject.csproj

    - name: Build Solution
      run: dotnet build ./CICDProject/CICDProject/CICDProject.csproj --configuration Release --no-restore

    - name: Run Unit Tests with Code Coverage
      run: |
        dotnet test ./CICDProject/CICDApi.UnitTests/CICDApi.UnitTests.csproj \
        --configuration Release \
        --logger "trx;LogFileName=test-results.trx" \
        /p:CollectCoverage=true \
        /p:CoverletOutput=./TestResults/ \
        /p:CoverletOutputFormat=cobertura \
        /p:Threshold=70 \
        /p:ThresholdType=line \
        /p:ThresholdStat=total

    # - name: Find Coverage File
    #   run: find ./TestResults -name "coverage.cobertura.xml"

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: |
        reportgenerator \
        -reports:./CICDProject/CICDApi.UnitTests/TestResults/coverage.cobertura.xml \
        -targetdir:coveragereport \
        -reporttypes:"Html;MarkdownSummary"

    - name: Display Coverage Summary
      run: cat coveragereport/Summary.md

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: CodeCoverageReport
        path: coveragereport

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ./CICDProject/CICDApi.UnitTests/TestResults

    - name: Publish
      run: |
        dotnet publish ./CICDProject/CICDProject/CICDProject.csproj \
           --configuration Release \
           --no-build \
           --output ./publish

    - name: Upload Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PublishedAPI
        path: ./publish